import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./pages/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body className="font-sans antialiased bg-gray-50">
    <div className="flex h-screen">


      <div className="w-64 bg-gray-800 text-white shadow-md">
        <Sidebar />
      </div>

      <div className="flex-1 p-6 bg-gray-100 overflow-auto">
        {children}
      </div>
      
    </div>
  </body>
</html>

  );
}
